dist: xenial

services:
  - docker

language: minimal

env:
  global:
    - DOCKER_USERNAME=gavinmroy
    - secure: "t4JlVndZahLfWFldIbouudSe5JkB3VhyQhwvZ9oj9AnxcP7Z4hcXVmq4Ba2ahGdCmoEC49l+jssezWLt1/L2pXoz31gWE7dfMKvd4yD8TJ/D4hD2l5k/KF8x5X0Qpa3sZAR9gaDLF/EuNcmphNpVXPB6hR9BHr2UGLG/lQhSYqTeI80ets47TWzhDmneWThPex8DNhjpfoqDLLM1wm2peH1O3NWNNSGzZQjggUR22HnRjU6OXNQw6w3P+OXyp3yDQB39DpDdMnH97rTYnDHSzSvbTQuWBJnugeQ1HAkYg9yBGB2NTnYBT0ECF+g3Tf/i59wQM53aZ1Qy6o0NPrSTBfMEoHact+ukCiOVqo9Q7yO+1yobbBxnd4slzHMwPW0ZBgEYNwJUsTUA1kqjoShPm8/RKxzbNumbKZ69I8/71WxR2CD6TQmIfWSqrvvqagEOUAQfJnbH/wZvlJPxFQ/O3ui2jTFLdTwI3wQrjvnFy95BmsAgLGCz34NuxfGBClpi5myO39W1JmpM94pxVrCZmYSpwksuGpooEuGkF0PbYyOtSDMpm34vtAEmOnVJZqd/vPGtBiuLosmRlLirfuHP2Ih75u/S4/nQK4KgKsRoZ+RbbRgiXNRqAu9bUIqizHm2ZtsAoFIbXQH45Gxvv79Vh5a61sK5kA1gZKZJzsihz6A="

stages:
  - name: deploy latest
    if: branch = master AND repo = gmr/alpine-redis
  - name: deploy tag
    if: tag IS present AND repo = gmr/alpine-redis

before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: true
after_script: rm /home/travis/.docker/config.json

jobs:
  include:
    - stage: deploy latest
      script: docker build -t gavinmroy/alpine-redis:latest .
      after_success: docker push gavinmroy/alpine-redis:latest
    - stage: deploy tag
      script: docker build -t gavinmroy/alpine-redis:latest .
      after_success:
        - docker push gavinmroy/alpine-redis:latest
        - docker tag gavinmroy/alpine-redis:latest gavinmroy/alpine-redis:${TRAVIS_TAG}
        - docker push gavinmroy/alpine-redis:${TRAVIS_TAG}
